
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000

  cache:
    ehcache:
      config: ehcache.xml
    type: ehcache


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



server:
  servlet:
    context-path: /
  port: 8080
