spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1

  freemarker:
    template-loader-path: classpath:/templates/
    charset: utf-8
    cache: false
    suffix: .ftl


logging:
  level:
    cn.pys.mapper: debug

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: cn.pys.entity
